plugin:
    name: 'axen.sso::lang.plugin.name'
    description: 'axen.sso::lang.plugin.description'
    author: Axen
    icon: oc-icon-user
    homepage: ''
navigation:
    main-menu-item:
        label: Users
        url: axen/sso/user
        icon: icon-life-ring
        sideMenu:
            shouser-menu-item:
                label: 'List Users'
                url: axen/sso/user
                icon: icon-sitemap
            userlog:
                label: 'User Log'
                url: axen/sso/userlog
                icon: icon-clock-o