list: $/axen/sso/models/log/columns.yaml
modelClass: Axen\Sso\Models\Log
title: UserLog
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
