# ===================================
#  Import/Export Behavior Config
# ===================================
export:
    title: Export users
    modelClass: Axen\Sso\Models\UserExport
    list: $/axen/sso/models/user/columns.yaml
    filename: users.csv

defaultFormatOptions:
    delimiter: ';'
    enclosure: '"'
    escape: '\'
    encoding: 'utf-8'

