name: User
form: $/axen/sso/models/user/fields.yaml
modelClass: Axen\Sso\Models\User
defaultRedirect: axen/sso/user
create:
    redirect: 'axen/sso/user/update/:id'
    redirectClose: axen/sso/user
update:
    redirect: axen/sso/user
    redirectClose: axen/sso/user
