list: $/axen/sso/models/user/columns.yaml
modelClass: Axen\Sso\Models\User
title: User
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'axen/sso/user/update/:id'
